nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
php:
  build: images/php
  volumes:
    - ./images/php/recipo_api:/app
  working_dir: /app/public
  command: php-fpm
  links:
    - db
    - cache
  ports:
    - "9000:9000"
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: SomeRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: recipo
    DB_USERNAME: root
    DB_PASSWORD: secret
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: recipo
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
cache:
  image: memcached
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
     - db
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=db
     - PMA_PORT=3306
     - PMA_USER=root
     - PMA_PASSWORD=secret
    restart: always
    ports:
     - 1234:80
    volumes:
     - /sessions
